【InReview】演習12_1【PR】
ddt-shirabe/meikai_java_shirabe pull request #1
Opened 2022-03-09 12:22 UTC by ddt-shirabe

**演習12_1プルリクエスト**
* Car2 － P324に記載された自動車クラス。
* CarInfo － 総走行距離を表すフィールドと、その値を調べるメソッドを追加した自動車クラス。
* Enshu12_1_Test － CarInfoテストクラス

2022-04-20 12:02 UTC, ddt-mentor requested changes

2022-04-20 12:02 UTC, ddt-mentor commented on CarInfo.java
> +	// TODO 自動生成されたコンストラクター・スタブ
柴田
Todoコメントは削除してください。
そもそもメソッドに対しコメントがありません。

2022-04-20 12:02 UTC, ddt-mentor commented on CarInfo.java
> +		this.mileage = mileage;
柴田
自分自身に自分自身を代入しています。
この処理(ここの1行)では何をしたいのか、から、確認してください。

2022-04-20 12:02 UTC, ddt-mentor commented on Enshu12_1_Test.java
> +		if(carNum == 1){
柴田
1、2のマジックナンバーとなっていますので、定数化して数値に意味を持たせてください。

2022-04-20 12:02 UTC, ddt-mentor commented on Enshu12_1_Test.java
> +			// ここでcarNumの入力に戻らせる。（while文？）
柴田
疑問形のまま処理を終わらせないでください。
分からない場合は確認してください。
敢えてそうしている場合は理由を記載してください。

2022-04-20 12:02 UTC, ddt-mentor commented on Enshu12_1_Test.java
> +		while(true){
柴田
無限ループは（演習で指定がない限り）使用しないでください。
処理が停止しない等、バグの温床になります。また、どこで終わるかも分かりづらくなります。

2022-04-20 12:02 UTC, ddt-mentor commented on Enshu12_1_Test.java
> +			car = new CarInfo("セレナ", 1500, 1000, 4500, 2000 ,new Day(2022,1,26));
柴田
上の選択肢では日産セレナなのに、ここではセレナとなっていますね。
こういうのも定数化（本来はDB等外部Inputから取得）すべきです。

2022-04-20 12:02 UTC, ddt-mentor commented on Car2.java
> +	}
柴田
車幅：セレナ㎜
車高：セレナ㎜
車長：セレナ㎜

2022-04-20 12:02 UTC, ddt-mentor commented on Car2.java
> +	private int length;
柴田
Eclipseで開発できている場合、黄色の警告が出ているはずです。
警告を確認することで、事前にバグや不備などをつぶせる可能性が高まります
基本的に赤のエラーだけではなく、黄色の警告もすべて消すように意識してください。
※ここは下の指摘を解消すると解消されるかと思います。

2022-04-20 12:12 UTC, ddt-shirabe commented on Car2.java
> +	}
以下の通りに修正
	// スペックを表示
	public void putSpec(){
		System.out.println("名前：" + name );
		System.out.println("車幅：" + width + "mm");
		System.out.println("車高：" + height + "mm");
		System.out.println("車長：" + length + "mm");
	}

2022-04-20 12:14 UTC, ddt-shirabe commented on Car2.java
> +	private int length;
６６～６８行目修正により解決済み

2022-04-20 12:28 UTC, ddt-shirabe commented on Enshu12_1_Test.java
> +		if(carNum == 1){
下記定数を追加
		// セレナの番号（１番）
		int serenaNo = 1;
		// アルファードの番号（２番）
		int AlphardNo = 2;
if文内を下記に変更
		// セレナが選ばれた場合
		if(carNum == serenaNo){
			car = new CarInfo("セレナ", 1500, 1000, 4500, 2000 ,new Day(2022,1,26));
			// アルファードが選ばれた場合
		}else if(carNum == AlphardNo){
			car = new CarInfo("アルファード", 1500, 1000, 4500, 2000 ,new Day(2021,1,26));
　　　　～以下略～

2022-05-18 11:39 UTC, ddt-shirabe commented on Enshu12_1_Test.java
> +			car = new CarInfo("セレナ", 1500, 1000, 4500, 2000 ,new Day(2022,1,26));
用意された車の名前を「セレナ」に統一

> （本来はDB等外部Inputから取得）
本件では上記対応までは求められていないため、なしとさせて下さい。

2022-06-08 11:44 UTC, ddt-shirabe commented on CarInfo.java
> +	// TODO 自動生成されたコンストラクター・スタブ
TODOコメントを削除。
該当メソッドに「スーパークラスCar2を継承したCarInfoのコンストラクタ」である旨を記載。

2022-06-08 12:10 UTC, ddt-shirabe commented on CarInfo.java
> +		this.mileage = mileage;
該当行を削除

2022-07-06 12:00 UTC, merged